---

- name: OSX - set_fact - platform
  set_fact:
    platform: darwin
  when: ansible_distribution == "MacOSX"
  tags: [ always, facts ]

- name: Linux - set_fact - platform
  set_fact:
    platform: linux
  when: ansible_distribution != "MacOSX"
  tags: [ always, facts ]
